name: CI

on:
  delete

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - env:
          GITHUB_EVENT: ${{ toJSON(github) }}
        run: echo "$GITHUB_EVENT"
